services:
  - type: web
    name: bunna-tna-api
    env: ruby
    buildCommand: docker build -t bunna-tna-api .
    startCommand: docker run -p 10000:3000 -e DATABASE_URL=$DATABASE_URL bunna-tna-api
    envVars:
      - key: RAILS_ENV
        value: production
      - key: DATABASE_URL
        fromDatabase:
          name: bunnabank-TNA
          property: connectionString
